name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy via FTPS
        run: |
          lftp -e "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate false;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          mirror -R --delete ./ /public_html/;
          quit
          "
        env:
          FTP_SERVER: onehost-wphn112403.000nethost.com
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}